import {
  Armour,
  Cigar,
  EffectType,
  Food,
  Inventory,
  Item,
  ItemCategory,
  ItemSize,
  ItemType,
  SpecialItem,
  StatusType,
  Weapon,
} from './game_interfaces';

export const foodRations: Food[] = [
  {
    name: 'Silány',
    desc: 'száraz kenyér',
    type: ItemType.FOOD,
    category: ItemCategory.CONSUMABLE,
    uses: 1,
    heal: 0,
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.HEAL_HP,
        target: 'self',
        value: 0,
      },
    ],
  },
  {
    name: 'Szerény',
    desc: 'kemény sajt és aszalt gyümölcsök',
    type: ItemType.FOOD,
    category: ItemCategory.CONSUMABLE,
    uses: 2,
    heal: 1,
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.HEAL_HP,
        target: 'self',
        value: 1,
      },
    ],
  },
  {
    name: 'Elégséges',
    desc: 'szárított hús friss zöldségekkel',
    type: ItemType.FOOD,
    category: ItemCategory.CONSUMABLE,
    uses: 3,
    heal: 2,
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.HEAL_HP,
        target: 'self',
        value: 2,
      },
    ],
  },
  {
    name: 'Bőséges',
    desc: 'sülthús, puha kenyér és sütemény',
    type: ItemType.FOOD,
    category: ItemCategory.CONSUMABLE,
    uses: 4,
    heal: 3,
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.HEAL_HP,
        target: 'self',
        value: 3,
      },
    ],
  },
];

export const medicalItems: SpecialItem[] = [
  {
    name: 'Kötszerek',
    desc: 'Hófehér szövetköteg, amit a világon mindenhol használnak. A szövetnek enyhe alkohol szaga van.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc: '1 kis sebet gyógyít be',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SMALL_WOUND,
        target: 'self',
        value: 1,
      },
    ],
  },
  {
    name: 'Sebvarró tű és cérna',
    desc: 'Görbe fém tű és egy köteg erős cérna. A tű olyan éles, hogy alig érzed meg ahogy áthatol a bőrödön.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc: '2 kis sebet gyógyít be',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SMALL_WOUND,
        target: 'self',
        value: 2,
      },
    ],
  },
  {
    name: 'Fájdalomcsillapító',
    desc: 'Kis kapszula zsibbasztó anyagokkal, ízre enyhén édes.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc: 'Gyógyulsz 1 stresszt',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SP,
        target: 'self',
        value: 1,
      },
    ],
  },
  {
    name: 'Nyugtató füstölő',
    desc: 'Egyszerű fém füstölő nyugtató füvekkel, az illatától minden színesebb lesz.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: true,
    combat: false,
    effectDesc:
      'Gyógyulsz 2 stresszt és minden 1 mezőre lévő szövetséges karakter szintén gyógyul 1 stresszt',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SP,
        target: 'self',
        value: 2,
      },
      { type: EffectType.HEAL_SP, target: 'party', value: 1 },
    ],
  },
  {
    name: 'Sebforrasztó',
    desc: 'Egy rúnákkal televésett fémlap. Ha egy kemény tárgynak nekiütjük, elkezd felhevülni és képes beforrasztani bármilyen nyílt sebet.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc: 'Elállítja a vérzést',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.REMOVE_STATUS,
        target: 'self',
        status: StatusType.BLEED,
      },
    ],
  },
  {
    name: 'Fertőtlenítő kenőcs',
    desc: 'Különböző gyógyfüvekből és állati részekből kikevert kenőcs fém tubusban. Az illata olyan, mint a méznek és a rothadásnak.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc:
      'Tűzállóvá teszi és enyhíti az égett bőrt. Elállítja és megakadályozza az égést',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.REMOVE_STATUS,
        target: 'self',
        status: StatusType.BURN,
      },
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.FIRE_RES,
        duration: 10,
      },
    ],
  },
  {
    name: 'Ellenméreg',
    desc: 'Holtágiak és mérgező lények nyálmirigyeiből készült, halványzöld, keserű ital.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc: 'A legtöbb közönséges mérget hatástalanítja',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.REMOVE_STATUS,
        target: 'self',
        status: StatusType.POISON,
      },
    ],
  },
  {
    name: 'Gyógyító injekció',
    desc: 'Ikorból készült injekció, a szúrás után olyan mintha az egész tested vízbe dobták volna.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc: 'Azonnal begyógyít 1 kis sebet. Függőséget tud okozni',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SMALL_WOUND,
        target: 'self',
        value: 1,
      },
    ],
  },
  {
    name: 'Gyógyító főzet',
    desc: 'Ikor alapú bájital viasszal lezárt nehéz üvegben. A folyadék megállás nélkül kavarog benne.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: true,
    effectDesc:
      'Azonnal begyógyít 2 kis sebet. Nagyobb eséllyel függőséget tud okozni',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_SMALL_WOUND,
        target: 'self',
        value: 2,
      },
    ],
  },
  {
    name: 'Protézis',
    desc: 'Egy ideiglenes, állítható fém művégtag, amit szükség esetén műtét és érzéstelenítő nélkül fel lehet szerelni.',
    type: ItemType.MEDICAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc:
      'Egy nagy sebet semlegesít, de a végtaggal kapcsolatos próbákra hátrányt kapsz',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.HEAL_LARGE_WOUND,
        target: 'self',
        value: 1,
      },
    ],
  },
];

export const specialDrinks: SpecialItem[] = [
  {
    name: 'Busóvér',
    desc: 'Kúszóerdő kéreg vodka és füvekből készítik. Fekete, sűrű ital, olyan mintha kátrányt innál. Az illata olyan, mint az aszalt gyümölcsöké. Az íze kissé fémes.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc: '10 percig előnyt kapsz minden erőpróbábra.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.ADVANTAGE,
        duration: 10,
      },
    ],
  },
  {
    name: 'Az istenek könnye',
    desc: 'A tiszta ikort gyümölcsök levével, alkohollal és vízzel higítják fel. Kinézetre olyan, mint egy folyékony prizma. Nincs illata, ízre olyan, mint egy szivárvány.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc:
      '5 percig a következő varázslatod ár megfizetése nélkül tudod használni.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.FREE_MAGIC,
        duration: 5,
      },
    ],
  },
  {
    name: 'Tündérméz',
    desc: 'A tündérligeti fák édes gyantájából és gyümölcslikőrből készítik. Úgy néz ki, mint a higított, szürke méz. Ízre olyan, mint egy szerető bőrének.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc:
      'Erős altató hatása van, akár egy napon keresztül is alszik az elfogyasztója, ha meg nem zavarják.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'target',
        status: StatusType.SLEEP,
        duration: 10000,
      },
    ],
  },
  {
    name: 'Bitómámor',
    desc: 'Erős vodka és füvek egyvelege, a kivégzés előtti embereknek szokták adni, hogy megnyugtassák őket. Olyan az íze, mint az illóolajnak.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc:
      'Egy óráig nem tud idegösszeroppanást kapni az elfogyasztója, a hatás lejárta után viszont az összes elszenvedett stressz sebzést megkapja.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.STRESS_RES,
        duration: 30,
      },
    ],
  },
  {
    name: 'Monyóktej',
    desc: 'Tejből, gyümölcspálinkából és gyümölcsléből készítik a ligeti pásztorok. A pálinka és gyümölcslé fajtája mindig megegyezik. Az üvegben a gyümölcsdarabok folyamatosan hullanak, mint a levelek, az íze olyan, mint az édes titkoknak.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc: '10 percig beszélni tudsz az állatok nyelvén a környezetedben.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.ANIMAL_TOUNGE,
        duration: 10,
      },
    ],
  },
  {
    name: 'Sen Altio',
    desc: 'Hófehér rum, virágok és tengeri növényekből forralják össze. Az üvegcserepes város nemzeti itala. Az íze keserű, mint a búcsúé.',
    type: ItemType.SPECIAL,
    category: ItemCategory.CONSUMABLE,
    isPartyWide: false,
    combat: false,
    effectDesc: 'A táborozásnál felér egy elégséges étkezéssel.',
    size: ItemSize.NORMAL,
    uses: 1,
    effects: [
      {
        type: EffectType.ADD_STATUS,
        target: 'self',
        status: StatusType.FULL_BELLY,
        duration: 1,
      },
    ],
  },
];

export const specialItems = medicalItems.concat(specialDrinks);
export const inventories: Inventory[] = [
  {
    name: 'Fűszeres tarisznya',
    desc: 'Egy fűszeres tarisznya (4 hely) (növények)',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 4,
    canStore: [ItemType.SPICE],
    storage: [],
    size: ItemSize.NORMAL,
  },

  {
    name: 'Nyílpuska tok',
    desc: 'Egy 15 nyilas nyílpuska tok',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 15,
    canStore: [ItemType.AMMO],
    storage: [],
    size: ItemSize.NORMAL,
  },

  {
    name: 'Íj tok',
    desc: 'Egy 10 nyilas íj tok',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 10,
    canStore: [ItemType.AMMO],
    storage: [],
    size: ItemSize.NORMAL,
  },

  {
    name: 'Pisztoly tártáska',
    desc: 'Egy 25 töltényes tártáska pisztolyhoz',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 25,
    canStore: [ItemType.AMMO],
    storage: [],
    size: ItemSize.NORMAL,
  },

  {
    name: 'Puska tártáska',
    desc: 'Egy 20 töltényes tártáska puskához',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 20,
    canStore: [ItemType.AMMO],
    storage: [],
    size: ItemSize.NORMAL,
  },

  {
    name: 'Üres zsák',
    desc: 'Egy üres zsák (5 hely)',
    type: ItemType.BAG,
    category: ItemCategory.INVENTORY,
    space: 5,
    canStore: [
      ItemType.COMMON,
      ItemType.FOOD,
      ItemType.SPECIAL,
      ItemType.WEAPON,
      ItemType.ARMOUR,
      ItemType.AMMO,
      ItemType.SPICE,
    ],
    storage: [],
    size: ItemSize.NORMAL,
  },
];

export const weapons: Weapon[] = [
  {
    name: 'Tőr',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd4',
    price: 10,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Pálca',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd4',
    price: 12,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Ostor',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd4',
    price: 15,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kard',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 20,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hosszúkard',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 30,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Rapír',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 25,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Szablya',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 22,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fejsze',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 18,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csatabárd',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd8',
    price: 35,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Buzogány',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 20,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Lándzsa',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 24,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Acél öklök',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 2,
    damage: 'd4',
    price: 28,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kalapács',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 20,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Pöröly',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd8',
    price: 32,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fokos',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd6',
    price: 26,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Íj',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd10',
    price: 40,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Számszeríj',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd10',
    price: 50,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Pisztoly',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd12',
    price: 60,
    handed: 1,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Karabély',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd12',
    price: 75,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kézi ágyú',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 3,
    damage: 'd6',
    price: 100,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kézi balliszta',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 1,
    damage: 'd20',
    price: 120,
    handed: 2,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Üres',
    desc: '',
    type: ItemType.WEAPON,
    category: ItemCategory.EQIUPMENT,
    diceCount: 0,
    damage: '',
    price: 0,
    handed: 0,
    size: ItemSize.NORMAL,
  },
];

export const armours: Armour[] = [
  {
    name: 'Ruha',
    desc: '',
    type: ItemType.ARMOUR,
    category: ItemCategory.EQIUPMENT,
    defValue: 1,
    dexMod: 0,
    price: 15,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Könnyű páncél',
    desc: '',
    type: ItemType.ARMOUR,
    category: ItemCategory.EQIUPMENT,
    defValue: 2,
    dexMod: 0,
    price: 25,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Nehéz páncél',
    desc: '',
    type: ItemType.ARMOUR,
    category: ItemCategory.EQIUPMENT,
    defValue: 3,
    dexMod: -1,
    price: 35,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Sétáló erőd',
    desc: '',
    type: ItemType.ARMOUR,
    category: ItemCategory.EQIUPMENT,
    defValue: 5,
    dexMod: -2,
    price: 55,
    size: ItemSize.NORMAL,
  },
];

export function getWeapon(idx: number) {
  return weapons[idx];
}

export function getArmour(idx: number) {
  return armours[idx];
}

export const cigars: Cigar[] = [
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Piros',
    spice: 'Paprika és bors',
    effectDesc: '+1 erő 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'str',
        value: 1,
        duration: 10,
      },
    ],
  },
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Zöld',
    spice: 'Alma és menta',
    effectDesc: '+1 ügyesség 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'dex',
        value: 1,
        duration: 10,
      },
    ],
  },
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Szürke',
    spice: 'Dió és fahéj',
    effectDesc: '+1 kitartás 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'end',
        value: 1,
        duration: 10,
      },
    ],
  },
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Lila',
    spice: 'Leander és rózsa',
    effectDesc: '+1 ész 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'int',
        value: 1,
        duration: 10,
      },
    ],
  },
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Sárga',
    spice: 'Citrus és vadvirágok',
    effectDesc: '+1 fortély 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'cun',
        value: 1,
        duration: 10,
      },
    ],
  },
  {
    name: 'Fűszeres cigaretta',
    desc: 'Egy kézzel sodort cigaretta különböző fűszerekkel töltve.',
    type: ItemType.CIGAR,
    category: ItemCategory.CONSUMABLE,
    color: 'Kék',
    spice: 'Búzavirág és kamilla',
    effectDesc: '+1 akaraterő 10 percig',
    size: ItemSize.NORMAL,
    effects: [
      {
        type: EffectType.BUFF_STAT,
        target: 'self',
        stat: 'wil',
        value: 1,
        duration: 10,
      },
    ],
  },
];

export const items: Item[] = [
  {
    name: 'Fa kereplő',
    desc: 'Egy fa kereplő',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Üres fiolák',
    desc: 'Üres fiolák, 5 darab',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Üres könyv és írótoll',
    desc: 'Egy üres könyv és írótoll',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Aranyréti pipafű',
    desc: 'Aranyréti pipafű, 10 töltés',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csikóbőrös kulacs',
    desc: 'Egy csikóbőrös kulacs',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Élezett olló',
    desc: 'Egy mindkét oldalán élezett olló (1d4)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Összecsukható horgászbot',
    desc: 'Egy összecsukható horgászbot',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kender kötél',
    desc: 'Egy 15 méter hoszú kender kötél',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csengő füzér',
    desc: 'Egy 5 méter hosszú csengő füzér',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Szakadt hálózsák',
    desc: 'Egy szakadt hálózsák (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Varrókészlet',
    desc: 'varrókészlet (P)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.SMALL,
  },
  {
    name: 'Távcső',
    desc: 'Egy távcső',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Beazonosíthatatlan pálinka',
    desc: 'Egy üveg beazonosíthatatlan pálinka',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Farkasfű csokor',
    desc: 'Egy csokor farkasfű, teriantrópok gyűlölik',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Bőr kesztyű',
    desc: 'Egy pár vastag bőr kesztyű',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Ősi isten képmása',
    desc: 'Egy ősi isten faragott képmása',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Nyugati Szentek jele',
    desc: 'A Nyugati Szentek jele',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hamis aranypénz',
    desc: 'Egy tarisznya hamis aranypénz (25g)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hosszú pipa',
    desc: 'Egy meglepően hosszú pipa, 5 pipafű',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Színes üveggolyók',
    desc: 'Színes üveggolyók',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Pakli kártya',
    desc: 'Egy pakli kártya',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csont dobókockák',
    desc: 'Négy csontból faragott dobókocka (P)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.SMALL,
  },
  {
    name: 'Brékakk tábla',
    desc: 'Egy brékakk tábla fa figurákkal',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fém lánc',
    desc: 'Egy 5 méteres fém lánc',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Folyékony ezüst',
    desc: 'Egy üvegcse folyékony ezüst, levegőt érve megszilárdul (P)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.SMALL,
  },
  {
    name: 'Színházi maszk',
    desc: 'Egy különös színházi maszk',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Állatfejes sétapálca',
    desc: 'Egy állatfejes sétapálca',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Színváltó kristály',
    desc: 'Egy színváltó kristály',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Iránytű',
    desc: 'Egy iránytű ami mindig dél fele mutat',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Zárfeltörő készlet',
    desc: 'Zárfeltörő készlet (5 használat)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Rozsdás olajlámpás',
    desc: 'Egy rozsdás olajlámpás',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kanna olaj',
    desc: 'egy kanna olaj (R)',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.LARGE,
  },
  {
    name: 'Kovakő és acélrúd',
    desc: 'Egy Kovakő és acélrúd',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fehér fenőkő',
    desc: 'Egy fehér fenőkő',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Mézes szappan',
    desc: 'Egy mézes illatú szappan',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Libatollas párna',
    desc: 'Egy libatollas párna',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Repedt tükör',
    desc: 'Egy repedt tükör',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Füstölők',
    desc: 'Felismerhetetlen illatú füstölők, 3 darab',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Bronz kutyasíp',
    desc: 'Egy bronz kutyasíp (P)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.SMALL,
  },
  {
    name: 'Fénylő por',
    desc: 'Eg borítéknyi fénylő por',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csont furulya',
    desc: 'Egy csontból faragott furulya',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Világító festék',
    desc: 'Egy tubus sötétben világító festék',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Étkészlet',
    desc: 'Egy étkészlet (kanál villa kés)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Monokli',
    desc: 'Egy több lencsés monokli',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Szögek',
    desc: 'Egy csomag szög',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Játékbaba',
    desc: 'Egy ismeretlen eredetű játékbaba',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fűrész',
    desc: 'Egy megerősített fogú fűrész',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Ecsetkészlet',
    desc: 'Egy ecsetkészlet és 10 rajzlap',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hamisított pecsét',
    desc: 'Egy hamisított udvari pecsét, 1 rúd viasz (5 használat)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hófehér borítékok',
    desc: 'Hófehér borítékok (15 darab)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fésű',
    desc: 'Egy fésű tüskenádból',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Ellenméreg',
    desc: 'Egy üvegcse ellenméreg',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Faszén',
    desc: 'Egy zsák faszén (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Szárított virágok',
    desc: 'Egy boríték szárított virág és füvek',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Tea filter',
    desc: 'Tea filter (10 darab) (P)',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.SMALL,
  },
  {
    name: 'Smink készlet',
    desc: 'Egy fém dobozos smink készlet',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Viasz gyertyák',
    desc: 'Vörös viasz gyertyák (5 darab)',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Bogrács',
    desc: 'Egy kovácsolt vas bogrács (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Váltóruha',
    desc: 'Váltóruha (Ing, Mellény, Nadrág, Egyberuha, Alsónemű, Zoknik)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Bakancs',
    desc: 'Egy pár acélbetétes bakancs',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Lópokróc',
    desc: 'Egy vastag, terepszínű lópokróc',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Sátor',
    desc: 'Egyszemélyes sátor (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Fémlakatos láda',
    desc: 'Fémlakatos láda (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Bályitalos üvegek',
    desc: 'Üres bályitalos üvegek, 5 darab',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Templomi harang',
    desc: 'Egy díszes templomi harang',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Hegymászó eszközök',
    desc: 'Hegymászó eszközök (csákány, kötél, fém szögek)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Ördög fejes lakat',
    desc: 'Egy nehéz, ördög fejes lakat',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fa tálak',
    desc: 'Fa tálak, 5 darab',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Elhangolt gitár',
    desc: 'Egy elhangolt gitár',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csavart vadászkürt',
    desc: 'Egy csavart vadászkürt',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kötéllétra',
    desc: 'Egy 10 méteres kötéllétra (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Kopott feszítővas',
    desc: 'Egy kopott feszítővas',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Medvecsapda',
    desc: 'Medvecsapda (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Hurokcsapdák',
    desc: 'Hurokcsapdák vadászathoz (nyúl, mókus, patkány)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fáklya',
    desc: 'Fém szögecses fáklya, 3 darab',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fém vödör',
    desc: 'Egy tiszta fém vödör (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Fehér kréta',
    desc: 'Egy csomag fehér kréta',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Kézi mérleg',
    desc: 'Egy kézi mérleg',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Selyem kötél',
    desc: 'Selyem kötél, 10 méter',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Finom parfüm',
    desc: 'Egy üveg finom parfüm',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Vastüskék',
    desc: 'Vastüskék 20 darab',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Fafaragó készlet',
    desc: 'Fafaragó készlet',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Csákány',
    desc: 'Egy csákány (1d6) (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Ásó',
    desc: 'Egy ásó (1d6) (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Favágó fejsze',
    desc: 'Favágó fejsze (1d6) (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Emberi koponya',
    desc: 'Egy tökéletes állapotú emberi koponya',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Injekciós tűk',
    desc: 'Üres injekciós tűk élezhető heggyel, 6 darab',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Szárított pirospaprika',
    desc: 'Egy füzér szárított pirospaprika',
    type: ItemType.COMMON,
    category: ItemCategory.CONSUMABLE,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Szerszám készlet',
    desc: 'Egy megbízható szerszám készlet (R)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.LARGE,
  },
  {
    name: 'Orvosi eszközök',
    desc: 'Koptatott orvosi eszközök',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Vas serpenyő',
    desc: 'Egy öntött vas serpenyő (1d4)',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Homokóra',
    desc: 'Egy folyamatosan járó homokóra',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Bilincs kulccsal',
    desc: 'Egy erős bilincs kulccsal',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
  {
    name: 'Vaddisznó agyar',
    desc: 'Egy faragott vaddisznó agyar',
    type: ItemType.COMMON,
    category: ItemCategory.GENERAL,
    size: ItemSize.NORMAL,
  },
];
