import { Component } from '@angular/core';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { Item } from '../character_interfaces';

@Component({
  selector: 'app-character-items',
  imports: [MatTableModule],
  templateUrl: './character-items.component.html',
  styleUrls: ['./character-items.component.scss', '../character_shared.scss'],
})
export class CharacterItemsComponent {
  items: Item[] = [
    { name: 'Fa kereplő', desc: 'Egy fa kereplő' },
    { name: 'Üres fiolák', desc: 'Üres fiolák, 5 darab' },
    { name: 'Üres könyv és írótoll', desc: 'Egy üres könyv és írótoll' },
    { name: 'Aranyréti pipafű', desc: 'Aranyréti pipafű, 10 töltés' },
    { name: 'Csikóbőrös kulacs', desc: 'Egy csikóbőrös kulacs' },
    { name: 'Élezett olló', desc: 'Egy mindkét oldalán élezett olló (1d4)' },
    { name: 'Összecsukható horgászbot', desc: 'Egy összecsukható horgászbot' },
    { name: 'Kender kötél', desc: 'Egy 15 méter hoszú kender kötél' },
    { name: 'Csengő füzér', desc: 'Egy 5 méter hosszú csengő füzér' },
    { name: 'Szakadt hálózsák', desc: 'Egy szakadt hálózsák (R)' },
    { name: 'Varrókészlet', desc: 'varrókészlet (P)' },
    { name: 'Távcső', desc: 'Egy távcső' },
    {
      name: 'Beazonosíthatatlan pálinka',
      desc: 'Egy üveg beazonosíthatatlan pálinka',
    },
    {
      name: 'Farkasfű csokor',
      desc: 'Egy csokor farkasfű, teriantrópok gyűlölik',
    },
    { name: 'Bőr kesztyű', desc: 'Egy pár vastag bőr kesztyű' },
    {
      name: 'Fűszeres tarisznya',
      desc: 'Egy fűszeres tarisznya (4 hely) (növények)',
    },
    { name: 'Ősi isten képmása', desc: 'Egy ősi isten faragott képmása' },
    { name: 'Nyugati Szentek jele', desc: 'A Nyugati Szentek jele' },
    { name: 'Hamis aranypénz', desc: 'Egy tarisznya hamis aranypénz (25g)' },
    { name: 'Nyílpuska tok', desc: 'Egy 15 nyilas nyílpuska tok' },
    { name: 'Íj tok', desc: 'Egy 10 nyilas íj tok' },
    {
      name: 'Pisztoly tártáska',
      desc: 'Egy 25 töltényes tártáska pisztolyhoz',
    },
    { name: 'Puska tártáska', desc: 'Egy 20 töltényes tártáska puskához' },
    { name: 'Hosszú pipa', desc: 'Egy meglepően hosszú pipa, 5 pipafű' },
    { name: 'Színes üveggolyók', desc: 'Színes üveggolyók' },
    { name: 'Pakli kártya', desc: 'Egy pakli kártya' },
    { name: 'Csont dobókockák', desc: 'Négy csontból faragott dobókocka (P)' },
    { name: 'Brékakk tábla', desc: 'Egy brékakk tábla fa figurákkal' },
    { name: 'Fém lánc', desc: 'Egy 5 méteres fém lánc' },
    {
      name: 'Folyékony ezüst',
      desc: 'Egy üvegcse folyékony ezüst, levegőt érve megszilárdul (P)',
    },
    { name: 'Színházi maszk', desc: 'Egy különös színházi maszk' },
    { name: 'Állatfejes sétapálca', desc: 'Egy állatfejes sétapálca' },
    { name: 'Színváltó kristály', desc: 'Egy színváltó kristály' },
    { name: 'Iránytű', desc: 'Egy iránytű ami mindig dél fele mutat' },
    { name: 'Zárfeltörő készlet', desc: 'Zárfeltörő készlet (5 használat)' },
    { name: 'Rozsdás olajlámpás', desc: 'Egy rozsdás olajlámpás' },
    { name: 'Kanna olaj', desc: 'egy kanna olaj (R)' },
    { name: 'Kovakő és acélrúd', desc: 'Egy Kovakő és acélrúd' },
    { name: 'Fehér fenőkő', desc: 'Egy fehér fenőkő' },
    { name: 'Mézes szappan', desc: 'Egy mézes illatú szappan' },
    { name: 'Libatollas párna', desc: 'Egy libatollas párna' },
    { name: 'Repedt tükör', desc: 'Egy repedt tükör' },
    { name: 'Füstölők', desc: 'Felismerhetetlen illatú füstölők, 3 darab' },
    { name: 'Bronz kutyasíp', desc: 'Egy bronz kutyasíp (P)' },
    { name: 'Fénylő por', desc: 'Eg borítéknyi fénylő por' },
    { name: 'Csont furulya', desc: 'Egy csontból faragott furulya' },
    { name: 'Világító festék', desc: 'Egy tubus sötétben világító festék' },
    { name: 'Étkészlet', desc: 'Egy étkészlet (kanál villa kés)' },
    { name: 'Monokli', desc: 'Egy több lencsés monokli' },
    { name: 'Szögek', desc: 'Egy csomag szög' },
    { name: 'Játékbaba', desc: 'Egy ismeretlen eredetű játékbaba' },
    { name: 'Fűrész', desc: 'Egy megerősített fogú fűrész' },
    { name: 'Ecsetkészlet', desc: 'Egy ecsetkészlet és 10 rajzlap' },
    {
      name: 'Hamisított pecsét',
      desc: 'Egy hamisított udvari pecsét, 1 rúd viasz (5 használat)',
    },
    { name: 'Hófehér borítékok', desc: 'Hófehér borítékok (15 darab)' },
    { name: 'Fésű', desc: 'Egy fésű tüskenádból' },
    { name: 'Ellenméreg', desc: 'Egy üvegcse ellenméreg' },
    { name: 'Faszén', desc: 'Egy zsák faszén (R)' },
    { name: 'Szárított virágok', desc: 'Egy boríték szárított virág és füvek' },
    { name: 'Tea filter', desc: 'Tea filter (10 darab) (P)' },
    { name: 'Smink készlet', desc: 'Egy fém dobozos smink készlet' },
    { name: 'Viasz gyertyák', desc: 'Vörös viasz gyertyák (5 darab)' },
    { name: 'Bogrács', desc: 'Egy kovácsolt vas bogrács (R)' },
    {
      name: 'Váltóruha',
      desc: 'Váltóruha (Ing, Mellény, Nadrág, Egyberuha, Alsónemű, Zoknik)',
    },
    { name: 'Bakancs', desc: 'Egy pár acélbetétes bakancs' },
    { name: 'Lópokróc', desc: 'Egy vastag, terepszínű lópokróc' },
    { name: 'Sátor', desc: 'Egyszemélyes sátor (R)' },
    { name: 'Fémlakatos láda', desc: 'Fémlakatos láda (R)' },
    { name: 'Bályitalos üvegek', desc: 'Üres bályitalos üvegek, 5 darab' },
    { name: 'Templomi harang', desc: 'Egy díszes templomi harang' },
    {
      name: 'Hegymászó eszközök',
      desc: 'Hegymászó eszközök (csákány, kötél, fém szögek)',
    },
    { name: 'Ördög fejes lakat', desc: 'Egy nehéz, ördög fejes lakat' },
    { name: 'Fa tálak', desc: 'Fa tálak, 5 darab' },
    { name: 'Elhangolt gitár', desc: 'Egy elhangolt gitár' },
    { name: 'Csavart vadászkürt', desc: 'Egy csavart vadászkürt' },
    { name: 'Kötéllétra', desc: 'Egy 10 méteres kötéllétra (R)' },
    { name: 'Kopott feszítővas', desc: 'Egy kopott feszítővas' },
    { name: 'Medvecsapda', desc: 'Medvecsapda (R)' },
    {
      name: 'Hurokcsapdák',
      desc: 'Hurokcsapdák vadászathoz (nyúl, mókus, patkány)',
    },
    { name: 'Üres zsák', desc: 'Egy üres zsák' },
    { name: 'Fáklya', desc: 'Fém szögecses fáklya, 3 darab' },
    { name: 'Fém vödör', desc: 'Egy tiszta fém vödör (R)' },
    { name: 'Fehér kréta', desc: 'Egy csomag fehér kréta' },
    { name: 'Kézi mérleg', desc: 'Egy kézi mérleg' },
    { name: 'Selyem kötél', desc: 'Selyem kötél, 10 méter' },
    { name: 'Finom parfüm', desc: 'Egy üveg finom parfüm' },
    { name: 'Vastüskék', desc: 'Vastüskék 20 darab' },
    { name: 'Fafaragó készlet', desc: 'Fafaragó készlet' },
    { name: 'Csákány', desc: 'Egy csákány (1d6) (R)' },
    { name: 'Ásó', desc: 'Egy ásó (1d6) (R)' },
    { name: 'Favágó fejsze', desc: 'Favágó fejsze (1d6) (R)' },
    { name: 'Emberi koponya', desc: 'Egy tökéletes állapotú emberi koponya' },
    {
      name: 'Injekciós tűk',
      desc: 'Üres injekciós tűk élezhető heggyel, 6 darab',
    },
    {
      name: 'Szárított pirospaprika',
      desc: 'Egy füzér szárított pirospaprika',
    },
    { name: 'Szerszám készlet', desc: 'Egy megbízható szerszám készlet (R)' },
    { name: 'Orvosi eszközök', desc: 'Koptatott orvosi eszközök' },
    { name: 'Vas serpenyő', desc: 'Egy öntött vas serpenyő (1d4)' },
    { name: 'Homokóra', desc: 'Egy folyamatosan járó homokóra' },
    { name: 'Bilincs kulccsal', desc: 'Egy erős bilincs kulccsal' },
    { name: 'Vaddisznó agyar', desc: 'Egy faragott vaddisznó agyar' },
  ];
  itemDataSource = new MatTableDataSource<Item>(this.items);
  displayedColumns: string[] = ['name', 'desc'];
}
